services:
#  app:
#    container_name: app_container
#    build:
#        context: .
#        dockerfile: Dockerfile
#    volumes:
#      - .:/var/www/html
#    ports:
#      - "9000:9000"

  database:
    image: postgres
    container_name: db_container
    environment:
      POSTGRES_DB: db_library
      POSTGRES_PASSWORD: passer
      POSTGRES_USER: root
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: adminer_library
    ports:
      - "8080:8080"
    depends_on:
      - database

volumes:
  database_data:
