controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_login:
    path:
        en: /login
        fr: /connexion
    methods: GET
app_logout:
    path:
        en: /login
        fr: /deconnexion
    methods: GET